# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x0fyfinance.protos\"\xb4\x01\n\nStockPrice\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12\x16\n\tdividends\x18\x07 \x01(\x01H\x00\x88\x01\x01\x12\x19\n\x0cstock_splits\x18\x08 \x01(\x01H\x01\x88\x01\x01\x42\x0c\n\n_dividendsB\x0f\n\r_stock_splits\"`\n\x0bStockPrices\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x14\n\x0cretrieved_at\x18\x02 \x01(\t\x12+\n\x06prices\x18\x03 \x03(\x0b\x32\x1b.yfinance.protos.StockPriceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKPRICE']._serialized_start=33
  _globals['_STOCKPRICE']._serialized_end=213
  _globals['_STOCKPRICES']._serialized_start=215
  _globals['_STOCKPRICES']._serialized_end=311
# @@protoc_insertion_point(module_scope)
